### ISSUE TITLE
Add Typescript Module Declarations

### ISSUE THREAD

**Issue by dungeongod** [cristovao-trevisan/vue-auto-virtual-scroll-list#11]
Add Typescript Module Declarations  for vue in typescipt users

**Comment by cristovao-trevisan** [comment]
May do so when I have some time, but PR's are welcomed

**Comment by cristovao-trevisan** [comment]
I tried to do it, but did not test it. @dungeongod , can you test it?

**Comment by dungeongod** [comment]
Sure,  I will test it.
