### ISSUE TITLE
Incorrect calculation when item is larger than container

### ISSUE THREAD

**Issue by chadananda** [cristovao-trevisan/vue-auto-virtual-scroll-list#16]
My item heights are not being adjusted after render. I assume this is because I am using a component for the list item. Is there a work-around?

```
<VueAutoVirtualScrollList :totalHeight="1400" :defaultHeight="100" style="width: 100%;" >
   <block v-for="block of blocks" :key="block.id" :style="{ height: `300px` }" />
</VueAutoVirtualScrollList>
```

**Comment by chadananda** [comment]
Seems to work when I remove style completely. However, it's very jumpy even on slow scrolling. I suspect because my items are quite large.

**Comment by cristovao-trevisan** [comment]
Do you have any items that are larger than the total height (or close to it)?

If you can provide any code that falls in your case I can fix it

**Comment by chadananda** [comment]
Yes, items can sometimes be larger than the visible page height. Sometimes the top item flashes on and off rapidly and at other times it is simply impossible to scroll smoothly up -- no matter how slowly.

**Comment by cristovao-trevisan** [comment]
The way things are now if items are larger than the `totalHeight` attr, the algorithm will fail.
I will look at this as soon as possible

**Comment by cristovao-trevisan** [comment]
Still not released. Working on #17

**Comment by cristovao-trevisan** [comment]
Published version 0.3.0 with the fix.
Can you try it out and reply if it works?

**Comment by chadananda** [comment]
Seems to have fixed the problem with oversized content flashing. However, scrolling up still incorrectly changes scroll position if the block immediately above the top is large.

**Comment by cristovao-trevisan** [comment]
I will only be able to see this again over the weekend (spent more time than
I thought on this), but I will fix it as soon as I can.
