### ISSUE TITLE
新增数据时，滚动条变为0

### ISSUE THREAD

**Issue by IHongTaoI** [cristovao-trevisan/vue-auto-virtual-scroll-list#2]
![image](https://user-images.githubusercontent.com/26668906/54671160-4f274d80-4b30-11e9-8382-c8a4ae683dce.png)

**Comment by cristovao-trevisan** [comment]
Can you explain the issue??
This library does not support dynamic lists, so when the items change it should reset the calculations (as of now I only check the list length to check for changes)

**Comment by cristovao-trevisan** [comment]
Closed due to unactivity
