### ISSUE TITLE
Travando a página

### ISSUE THREAD

**Issue by AldeirJampier** [cristovao-trevisan/vue-auto-virtual-scroll-list#24]
Olá amigo, ando fazendo alguns testes com seu plugin, e venho me deparando as vezes com travamentos, não são leves, realmente trava a aba em que o projeto está aberto. Sabe me informar o motivo?

**Comment by cristovao-trevisan** [comment]
Em geral isso se dá por loops infinitos, agora o que causa vem do seu código provavelmente.
Note que os únicos motivos de renderização é a alteração do scroll e modificação da altura dos items.
Se você quer saber se o loop está nesse componente joga um console.log no evento `updated`, mas é improvável

**Comment by cristovao-trevisan** [comment]
Fechando por inatividade, qualquer coisa só abrir de novo

**Comment by cristovao-trevisan** [comment]
Parece que o problema é na minha lib mesmo, dado o issue #25. Vou deixar esse aqui fechado e favorecer esse outro, por estar em inglês
